"""Core business logic for YouTube monitoring and translation."""

from .video_discovery import (
    VideoInfo,
    fetch_channel_videos,
    fetch_channel_videos_rss,
    extract_video_id,
    construct_video_url,
    filter_new_videos,
    filter_new_videos_rss,
    fetch_and_filter_videos,
    get_channel_id,
    get_rss_url,
)
from .content_fetcher import (
    VideoMetadata,
    fetch_video_info,
    get_video_info,
    download_subtitle,
    download_subtitles,
    check_video_availability,
    verify_subtitle_file,
    sanitize_filename,
)
from .subtitle_processor import (
    ProcessedSubtitles,
    process_subtitle_file,
    process_subtitle_text,
    split_by_chapters,
    get_segment_text,
    get_duration_from_entries,
    check_minimum_duration,
    validate_subtitles,
    estimate_subtitle_quality,
)
from .ai_analyzer import (
    ChapterInfo,
    AnalysisResult,
    analyze_video,
    generate_summary,
    call_claude_with_prompt,
    parse_chapters_from_summary,
    detect_video_type,
    extract_speakers,
    extract_intro,
    validate_analysis,
    generate_fallback_chapters,
)
from .translator import (
    TranslationResult,
    translate_chapter,
    translate_chapters,
    translate_all_chapters,
    call_claude_translate,
    validate_translation,
    estimate_translation_quality,
    combine_translations,
)
from .output_generator import (
    generate_markdown,
    save_output,
    validate_output,
    sanitize_filename,
    format_duration,
    combine_summary_and_translation,
    get_word_count,
)
from .pipeline import (
    PipelineResult,
    process_video,
    run_pipeline,
    run_loop,
    print_summary,
)

__all__ = [
    # video_discovery
    "VideoInfo",
    "fetch_channel_videos",
    "fetch_channel_videos_rss",
    "extract_video_id",
    "construct_video_url",
    "filter_new_videos",
    "filter_new_videos_rss",
    "fetch_and_filter_videos",
    "get_channel_id",
    "get_rss_url",
    # content_fetcher
    "VideoMetadata",
    "fetch_video_info",
    "get_video_info",
    "download_subtitle",
    "download_subtitles",
    "check_video_availability",
    "verify_subtitle_file",
    "sanitize_filename",
    # subtitle_processor
    "ProcessedSubtitles",
    "process_subtitle_file",
    "process_subtitle_text",
    "split_by_chapters",
    "get_segment_text",
    "get_duration_from_entries",
    "check_minimum_duration",
    "validate_subtitles",
    "estimate_subtitle_quality",
    # ai_analyzer
    "ChapterInfo",
    "AnalysisResult",
    "analyze_video",
    "generate_summary",
    "call_claude_with_prompt",
    "parse_chapters_from_summary",
    "detect_video_type",
    "extract_speakers",
    "extract_intro",
    "validate_analysis",
    "generate_fallback_chapters",
    # translator
    "TranslationResult",
    "translate_chapter",
    "translate_chapters",
    "translate_all_chapters",
    "call_claude_translate",
    "validate_translation",
    "estimate_translation_quality",
    "combine_translations",
    # output_generator
    "generate_markdown",
    "save_output",
    "validate_output",
    "format_duration",
    "combine_summary_and_translation",
    "get_word_count",
    # pipeline
    "PipelineResult",
    "process_video",
    "run_pipeline",
    "run_loop",
    "print_summary",
]
